apiVersion: v2
name: jellyfin
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "10.18.3"
maintainers:
  - name: Drew
    email: drew@hudson-viles.uk
keywords:
  - mediaserver
  - jellyfin
  - media
