---
# Default values for HA e2e-testing basic.

nginx:
  image:
    # -- The repo to be used
    repo: nginx
    # -- The tag to be used
    tag: 1.21-alpine
  serviceAccountName: "nginx"
  serviceMonitor:
    enabled: true
  resources: {}
    # requests:
    #   memory: "500Mi"
    #   cpu: "500m"
    # limits:
    #   memory: "1Gi"
    #   cpu: "1000m"

ingress:
  enabled: true
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # external-dns.alpha.kubernetes.io/target: "example.uk"
    # external-dns.alpha.kubernetes.io/hostname: "example.uk"
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  className: nginx
  host: test.example.uk
  tls:
    - hosts:
        - test.example.uk
      secretName: test-secret

postgres:
  image:
    # -- The repo to be used
    repo: postgres
    # -- The tag to be used
    tag: 14.1-bullseye
  serviceAccountName: postgresql
  statefulset:
    persistentData:
      enabled: true
      className: "fast-disks"
      size: 10Gi
    env:
      postgresPassword: "some-password"
      postgresUser: "some-user"
