---
# Default values for HA e2e-testing basic.

nginx:
  image:
    repo: nginx
    tag: 1.23.2-alpine
  resources: { }
  # requests:
  #   memory: "500Mi"
  #   cpu: "500m"
  # limits:
  #   memory: "1Gi"
  #   cpu: "1000m"

postgres:
  image:
    repo: postgres
    tag: 15.1-alpine
  statefulset:
    persistentData:
      enabled: true
      className: "fast-disks"
      size: 10Gi
    env:
      postgresPassword: "e2e-password"
      postgresUser: "e2e-user"
      postgresDB: "e2e-user"

ingress:
  enabled: true
  annotations: { }
  # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # external-dns.alpha.kubernetes.io/target: "example.uk"
  # external-dns.alpha.kubernetes.io/hostname: "example.uk"
  # external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  className: nginx
  host: test.example.uk
  tls: []
  #  - hosts:
  #      - test.example.uk
  #    secretName: test-secret

# Deploys a ServiceMonitor and dashboards to grafana for validation of Prometheus/monitoring.
monitoring:
  grafana:
    dashboards: false
  serviceMonitor:
    enabled: false

gpu:
  # Enable to deploy a workload for GPU testing.
  enabled: false
