---
# Default values for postgres.

image:
  # -- The repo to be used
  repo: postgres
  # -- The tag to be used
  tag: 14.1-bullseye

nameOverride: postgresql
namespace:
  name: database
serviceAccountName: postgresql

statefulset:
  replicas: 1
  resources: {}
  imagePullSecrets: {}
  podSecurityContext: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}

postgres:
  peristentData:
    enabled: false
  storage:
    className: fast-disks
    size: 1Gi
  service:
    type: LoadBalancer
    loadBalancerIP:
  env:
    postgresPassword: "SOME_PASSWORD"
    postgresUser: "SOME_USER"
    postgresDB: "SOME_USER_DB"
#    postgresInitDBArgs: ""
#    postgresInitDBWalDir: ""
#    hostAuthMethod: ""
#    pgData: ""
