apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "samba.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
data:
  smb.conf: |
    [global]
      workgroup = WORKGROUP
      netbios name = samba
      security = user
      map to guest = Bad User
      guest account = nobody
      max log size = 1000

    [shared]
      follow symlinks = yes
      wide links = yes
      browseable = yes
      writeable = yes
      valid users = {{ .Values.sambaUser }}
      path = /shared
      force user = {{ .Values.sambaUser }}
      force group = nogroup
      create mask = 0644
      directory mask = 0755