---
apiVersion: v1
name: drone-runner-kube
description: The Drone Kubernetes runner launches builds in Kubernetes Jobs
version: 0.1.0
appVersion: 1.0.0
kubeVersion: "^1.20.0-0"
home: https://github.com/drew-viles/charts/drone-runner-kube
icon: https://drone.io/apple-touch-icon.png
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://drew-viles.github.io/helm-charts
maintainers:
  - name: Drew
    email: drew@viles.uk
