persistentVolume:
  etc:
    size: 1Gi
  dns:
    size: 1Gi
  storageClassName: "longhorn"


webService:
  type: ClusterIP
  port: 80
  annotations: {}
dnsService:
  type: LoadBalancer
  port: 53
  annotations: {}
dhcpService:
  type: LoadBalancer
  port: 69
  annotations: {}
