apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{.Values.serviceAccountName}}
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
  annotations:
  {{- include "postgresql.annotations" . | nindent 4 }}
---