---
# Default values for postgres.

image:
  # -- The repo to be used
  repo: postgres
  # -- The tag to be used
  tag: 11.14-bullseye

nameOverride: postgresql
namespace:
  name: database
serviceAccountName: postgresql

statefulset:
  # -- Replicas
  replicas: 1
  # -- K8S Resources
  resources: {}
  # -- Image Pull secrets
  imagePullSecrets: {}
  # -- Pod Security Context
  podSecurityContext: {}
  # -- Node Selector
  nodeSelector: {}
  # -- Pod Affinity/AnitAffinity
  affinity: {}
  # -- Tolerations
  tolerations: {}

postgres:
  storage:
    className: fast-disks
    size: 1Gi
  service:
    type: LoadBalancer
    loadBalancerIP:
  env: {}
  # postgresPassword: ""
  # postgresUser: ""
  # postgresDB: ""
  # postgresInitDBArgs: ""
  # postgresInitDBWalDir: ""
  # hostAuthMethod: ""
  # pgData: ""
