---
apiVersion: v1
kind: Secret
metadata:
  name: operator-webhook-certs
  namespace: {{ .Values.operator.operatorNamespace.name }}
  labels:
    app.kubernetes.io/component: webhook
    operator.knative.dev/release: "v1.4.1"
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/part-of: knative-operator
  # The data is populated at install time.