---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: operator-webhook
    operator.knative.dev/release: "v1.4.1"
    app.kubernetes.io/component: operator-webhook
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/name: knative-operator
  name: operator-webhook
  namespace: {{ .Values.operator.operatorNamespace.name }}
spec:
  ports:
    # Define metrics and profiling for them to be accessible within service meshes.
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    role: operator-webhook
