---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-operator-post-install-job-role
  labels:
    operator.knative.dev/release: "v1.4.1"
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/part-of: knative-operator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
rules:
  # Storage version upgrader needs to be able to patch CRDs.
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
      - "customresourcedefinitions/status"
    verbs:
      - "get"
      - "list"
      - "update"
      - "patch"
      - "watch"
  # Our own resources we care about.
  - apiGroups:
      - "operator.knative.dev"
    resources:
      - "knativeservings"
      - "knativeeventings"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
      - "patch"
      - "watch"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-operator-post-install-job-role-binding
  labels:
    operator.knative.dev/release: "v1.4.1"
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/part-of: knative-operator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
subjects:
  - kind: ServiceAccount
    name: knative-operator-post-install-job
    namespace: {{ .Values.operator.operatorNamespace.name }}
roleRef:
  kind: ClusterRole
  name: knative-operator-post-install-job-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-operator-post-install-job
  namespace: {{ .Values.operator.operatorNamespace.name }}
  labels:
    operator.knative.dev/release: "v1.4.1"
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/part-of: knative-operator
  annotations:
    "helm.sh/hook": post-install,post-upgrade

---

apiVersion: batch/v1
kind: Job
metadata:
  generateName: storage-version-migration-operator-
  namespace: {{ .Values.operator.operatorNamespace.name }}
  labels:
    app: "storage-version-migration-operator"
    operator.knative.dev/release: "v1.4.1"
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/part-of: knative-operator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: "storage-version-migration-operator"
        operator.knative.dev/release: "v1.4.1"
        app.kubernetes.io/version: "1.4.1"
        app.kubernetes.io/part-of: knative-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: knative-operator-post-install-job
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:2c163f16f3de683946bdad5d817d954e75dacdaf8e9a103e1356bd44fb8f6b3b
          args:
            - "knativeservings.operator.knative.dev"
            - "knativeeventings.operator.knative.dev"