apiVersion: v2
name: virt-operator
type: application
version: 0.1.0
appVersion: "1.1.0"
description: |
  # Virt Operator for Kube Virt

  KubeVirt technology addresses the needs of development teams that have adopted or want to adopt Kubernetes but
  possess existing Virtual Machine-based workloads that cannot be easily containerized. More specifically,
  the technology provides a unified development platform where developers can build, modify, and deploy applications
  residing in both Application Containers as well as Virtual Machines in a common, shared environment.

  Benefits are broad and significant. Teams with a reliance on existing virtual machine-based workloads are empowered
  to rapidly containerize applications. With virtualized workloads placed directly in development workflows,
  teams can decompose them over time while still leveraging remaining virtualized components as is comfortably desired.

maintainers:
  - name: Drew
    email: drew@hudson-viles.uk
keywords:
  - virtualisation
  - kubevirt
sources:
  - https://drew-viles.github.io/helm-charts/virt-operator
