{{- if .Values.operator.istioNamespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.istioNamespace.name }}
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
    {{- include "istio-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "istio-operator.annotations" . | nindent 4 }}
---
{{- end}}