apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{.Values.operator.operatorNamespace.name}}
  name: istio-operator
  labels:
  {{- include "istio-operator.labels" . | nindent 4 }}
  annotations:
  {{- include "istio-operator.annotations" . | nindent 4 }}
---