apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.operator.operatorNamespace.name}}
  labels:
    name: istio-operator
  {{- include "istio-operator.labels" . | nindent 4 }}
  annotations:
  {{- include "istio-operator.annotations" . | nindent 4 }}
  name: istio-operator
spec:
  ports:
    - name: http-metrics
      port: 8383
      targetPort: 8383
  selector:
    name: istio-operator
---