{{- if .Values.gpu.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: gpu-test
  labels:
    app: gpu-test
    app.kubernetes.io/instance: gpu-test
    app.kubernetes.io/name: gpu-test
    {{- include "e2e-testing.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: gpu-test
    {{- include "e2e-testing.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-test
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      serviceAccountName: gpu-sa
      containers:
        - name: cuda-vectoradd
          image: "nvidia/samples:vectoradd-cuda11.2.1"
          resources:
            limits:
              nvidia.com/gpu: "1"
{{- end }}