---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-e2e
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: nginx-e2e
    {{- include "e2e-testing.annotations" . | nindent 4 }}
  labels:
    app: nginx-e2e
    app.kubernetes.io/instance: nginx-e2e
    app.kubernetes.io/name: nginx-e2e
    {{- include "e2e-testing.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: web-frontend