apiVersion: v1
kind: Service
metadata:
  name: database-e2e
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: postgres
    {{- include "e2e-testing.annotations" . | nindent 4 }}
  labels:
    app: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    {{- include "e2e-testing.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: sql
  selector:
    app: database-backend
  type: ClusterIP
