---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.postgres.serviceAccountName}}
  namespace: {{ .Release.Namespace }}
  labels:
    meta.helm.sh/release-name: postgres
    {{- include "e2e-testing.annotations" . | nindent 4 }}
  annotations:
    app: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    {{- include "e2e-testing.labels" . | nindent 4 }}