---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: web-database
  labels:
    app: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    {{- include "e2e-testing.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: postgres
    {{- include "e2e-testing.annotations" . | nindent 4 }}
spec:
  replicas: 3
  serviceName: database-e2e
  selector:
    matchLabels:
      app: database-backend
  template:
    metadata:
      labels:
        app: database-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: database-backend
                topologyKey: topology.kubernetes.io/zone
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web-frontend
                topologyKey: topology.kubernetes.io/zone
      serviceAccountName: postgresql-sa
      initContainers:
        - name: postgres-clean
          image: busybox:latest
          command:
            - /bin/sh
          args:
            - -c
            - rm -rf /var/lib/postgresql/data/*
            - rm -rf /var/lib/postgresql/data/.*
          {{- if (eq true .Values.postgres.statefulset.persistentData.enabled)}}
          volumeMounts:
            - name: data
              mountPath: "/var/lib/postgresql/data"
          {{- end}}
      containers:
        - name: postgres
          image: {{.Values.postgres.image.repo}}:{{.Values.postgres.image.tag}}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: passwd
                  name: pg-password
            - name: POSTGRES_USER
              value: {{.Values.postgres.statefulset.env.postgresUser}}
            - name: POSTGRES_DB
              value: {{.Values.postgres.statefulset.env.postgresDB}}
          ports:
            - containerPort: 5432
              name: sql
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            tcpSocket:
              port: 5432
          volumeMounts:
            - name: data
              mountPath: "/var/lib/postgresql/data"
            - name: init-data
              mountPath: "/docker-entrypoint-initdb.d"
      volumes:
        - name: init-data
          configMap:
            name: sql-init
            defaultMode: 0755
      {{- if (eq false .Values.postgres.statefulset.persistentData.enabled)}}
        - name: data
          emptyDir: { }
      {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{.Values.postgres.statefulset.persistentData.className}}
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{.Values.postgres.statefulset.persistentData.size}}
{{- end }}