---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: nginx-e2e
    {{- include "e2e-testing.annotations" . | nindent 4 }}
  labels:
    app: nginx-e2e
    app.kubernetes.io/instance: nginx-e2e
    app.kubernetes.io/name: nginx-e2e
    {{- include "e2e-testing.labels" . | nindent 4 }}
data:
  index: |
    <?php
      $servername = "database-e2e.{{ .Release.Namespace }}";
      {{- if .Values.postgres.statefulset.env.postgresUser }}
      $username = "{{ .Values.postgres.statefulset.env.postgresUser }}";
      {{- else }}
      $username = "root";
      {{- end }}
      $password = "{{ .Values.postgres.statefulset.env.postgresPassword }}";
      $arr = array("success" => false, "data" => "");
  
      try {
        $conn = new PDO("pgsql:host=$servername;port=5432;dbname=test", $username, $password);
        // set the PDO error mode to exception
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $stmt = $conn->query("SELECT value FROM web");
        $result = $stmt->fetch();
    
        if (!$result) {
          $arr['data'] = "not ok";
        }else{
          $arr['success'] = true;
          $arr['data'] = $result["value"];
        }
        $conn = null;
      } catch(PDOException $e) {
        $arr['success'] = false;
        $arr['data'] = "Connection failed: " . $e->getMessage();
      }
    
      header('Content-type: application/json');
      echo json_encode($arr);
    ?>