name: Lint and Test Charts

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:


jobs:

  ## Linting is broken: https://github.com/helm/chart-testing/issues/169
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run lint
        run: ct lint --all --config .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      # - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/yannh/kubernetes-json-schema
          - v1.26.9
          - v1.27.8
          - v1.28.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Run kubeconform
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeconform.sh