name: Lint and Test Charts

on:
  push:
    branches:
      - 'releases/**'
    paths:
      - 'charts/**'
  pull_request:
  workflow_dispatch:


jobs:

  ## Linting is broken: https://github.com/helm/chart-testing/issues/169
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.3.0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run lint
        run: ct lint --all --config .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      # - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/yannh/kubernetes-json-schema
          - v1.22.9
          - v1.23.9
          - v1.24.4
          - v1.25.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Run kubeconform
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeconform.sh